---
title: "Data Wrangling"
author: "Sophia Miller"
date: "9/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```
## Load a dataset

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
```

## Load second dataset

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```
```{r}
litters_data = read_csv(
  file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  ))
```

## Read in an excel file

```{r}
mlb11_data = 
  read_excel(
    path = "./data/mlb11.xlsx")
```

## Read in SAS file

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
```

## Exporting data

```{r}
mlb11_data_subset = 
  read_excel(
    path = "./data/mlb11.xlsx",
    range = "A1:D7")
```

```{r}
write.csv(mlb11_data_subset, path = "./data/mlb11_subset.csv" )
readr::read_csv
```




